[theme]
# 고정 테마 (macOS 라이트/다크 자동 전환 무시)
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#050910"
secondaryBackgroundColor = "#0f172a"
textColor = "#e2e8f0"
font = "Inter"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = false
